module.exports = {
  // User roles
  STUDENT: "STUDENT",
  ADMIN: "ADMIN",
  DEFAULT: "DEFAULT",

  // Room types
  SIX_PEOPLE: "SIX_PEOPLE",
  TWELVE_PEOPLE: "TWELVE_PEOPLE",

  R_STATUS_FULL: "FULL",
  R_STATUS_AVAILABLE: "AVAILABLE",
  // Request status

  // Payment status

  // Notification types

  // Alocation status
  ALLOCATION_APPROVED: "ALLOCATION_APPROVED",
  ALLOCATION_CANCELLED: "ALLOCATION_CANCELLED",
  ALLOCATION_EXPIRED: "ALLOCATION_EXPIRED",

  // Student status
  STU_ACTIVE: "STU_ACTIVE",
  STU_PENDING: "STU_PENDING",
  STU_INACTIVE: "STU_INACTIVE",

  // Room Allocation Status
  RA_STATUS_DANGKY: "DANGKY",
  RA_STATUS_DANGO: "DANGO",
};
