module.exports = {
  // User roles
  STUDENT: "STUDENT",
  ADMIN: "ADMIN",
  DEFAULT: "DEFAULT",

  // Room types
  SIX_PEOPLE: "SIX_PEOPLE",
  TWELVE_PEOPLE: "TWELVE_PEOPLE",

  R_STATUS_FULL: "FULL",
  R_STATUS_AVAILABLE: "AVAILABLE",
  R_STATUS_MAINTENANCE: "MAINTENANCE",
  // Request status

  // Payment Status
  PAYMENT_STATUS_PAID: "PAID",
  PAYMENT_STATUS_UNPAID: "UNPAID",
  PAYMENT_STATUS_OVERDUE: "OVERDUE",
  PAYMENT_STATUS_CANCELLED: "CANCELLED",

  // Payment Method
  PAYMENT_METHOD_CASH: "CASH",
  PAYMENT_METHOD_TRANSFER: "TRANSFER",
  PAYMENT_METHOD_CARD: "CARD",

  // Notification types

  // Alocation status
  ALLOCATION_APPROVED: "ALLOCATION_APPROVED",
  ALLOCATION_CANCELLED: "ALLOCATION_CANCELLED",
  ALLOCATION_EXPIRED: "ALLOCATION_EXPIRED",

  // Student status
  STU_ACTIVE: "STU_ACTIVE",
  STU_PENDING: "STU_PENDING",
  STU_INACTIVE: "STU_INACTIVE",

  // Room Allocation Status
  RA_STATUS_DANGKY: "DANGKY",
  RA_STATUS_DANGO: "DANGO",
  RA_STATUS_DAHUY: "DAHUY",
  RA_STATUS_KETTHUC: "KETTHUC",
};
